### ISSUE TITLE
[ERROR] http error [400]

### ISSUE THREAD

**Issue by cczhong11** [skygragon/leetcode-cli#100]
I could use leetcode-cli properly half hours ago. But now it only shows `[ERROR] http error [400]` with only `leetcode show 1`. I ensured my network is okay and I have login in my account. I am in US, no GFW problem. If this was just temporary problem, I will close this issue.

**Comment by anooprh** [comment]
+1 on the exact same issue !!

**Comment by caoyuan0816** [comment]
Same Issue, I'm in China right now. I can submit and test solutions but cannot use show command to download and generate question. It always show http error [400].

**Comment by si-yao** [comment]
+ 1 for US user.

**Comment by jdneo** [comment]
@skygragon May I ask what is the ETA for this new release?

**Comment by skygragon** [comment]
@guys, please tryout this latest fix and let me know if the issue is gone for you.

**Comment by cczhong11** [comment]
It works for me.

**Comment by jdneo** [comment]
@skygragon The `2.5.2` works perfectly fine! Thank you!
