### ISSUE TITLE
leetcode show fails with [ERROR] http error [400]

### ISSUE THREAD

**Issue by honghaoli** [skygragon/leetcode-cli#102]
since several days ago.

### Environment

- leetcode-cli version:

- OS version:
- Node version:
- Npm version:

 CLI v2.5.1
Node                 v6.9.1
OS                   darwin 17.5.0
[Configuration]
autologin            {"enable":false,"retry":2}
code                 {"editor":"vim","lang":"cpp"}
color                {"enable":true,"theme":"default"}
icon                 {"theme":""}
network              {"concurrency":10}

**Comment by mnlm1991** [comment]
npm install -g skygragon/leetcode-cli   use the github latest version

**Comment by honghaoli** [comment]
npm install -g skygragon/leetcode-cli  works, thanks!

**Comment by skygragon** [comment]
duplicated to #100
