### ISSUE TITLE
Could it support hackerrank ?

### ISSUE THREAD

**Issue by huangyingw** [skygragon/leetcode-cli#103]
I noticed a similiar project here:
https://github.com/andrewstuart/hr
But it is with Go, and I don't know how to build/install it.

**Comment by skygragon** [comment]
sounds like a plugin like lintcode

**Comment by huangyingw** [comment]
@skygragon 这很有用, leetcode是用来练习的, 而hackerrank是直接用来面试的,如果能够离线用自己最喜欢的IDE来做的话, 面试成绩可以快速提高.

**Comment by skygragon** [comment]
This issue was moved to skygragon/leetcode-cli-plugins#16
