### ISSUE TITLE
Something wrong with login in leetcode

### ISSUE THREAD

**Issue by leekaka** [skygragon/leetcode-cli#107]
### Environment

- leetcode-cli version:2.5.1

- OS version:win10
- Node version:
- Npm version:

![image](https://user-images.githubusercontent.com/29266786/40846445-3514d5ea-65ec-11e8-9ade-9d62ed727680.png)

**Comment by skygragon** [comment]
@leekaka could you try the latest code?
```
npm install -g skygragon/leetcode-cli
```

**Comment by skygragon** [comment]
duplicated to #92

**Comment by leekaka** [comment]
Thanks! everything is ok!
