### ISSUE TITLE
Could you show official solution articles?

### ISSUE THREAD

**Issue by yhuanghamu** [skygragon/leetcode-cli#113]
### Environment

- leetcode-cli version:

- OS version:
- Node version:
- Npm version:

**Comment by sfdye** [comment]
https://github.com/skygragon/leetcode-cli-plugins/blob/master/docs/solution.discuss.md

**Comment by yhuanghamu** [comment]
Hmm, i means `official article` not the solution in discuss.

**Comment by skygragon** [comment]
@yhuanghamu the article usually contains rich format like pictures and table layouts, which might not be suitable to display within terminal. Better to let browser do its job IMHO.
