### ISSUE TITLE
[ERROR] Error: getaddrinfo ENOTFOUND leetcode.com leetcode.com:443 [0]

### ISSUE THREAD

**Issue by jouw** [skygragon/leetcode-cli#116]
### Problem Summary

leetcode submit 884.decoded-string-at-index.cpp

![image](https://user-images.githubusercontent.com/1312493/44013778-523bd5a0-9efa-11e8-8f2f-781652baafdb.png)

### Environment

- leetcode-cli version: 2.5.2

- OS version: ubuntu 14.04
- Node version: v10.1.0
- Npm version: 5.6.0

**Comment by skygragon** [comment]
sounds like a network issue like #94 ?

**Comment by skygragon** [comment]
duplicate to #94
