### ISSUE TITLE
[WARN] Failed to retrieve user favorites: Error: socket hang up

### ISSUE THREAD

**Issue by QiangZiBro** [skygragon/leetcode-cli#118]
I tried to  login **leetcode login -l**  on my ubuntu,but have a wranning:
>[WARN] Failed to retrieve user favorites: Error: socket hang up

and always stay at:
>Retrieving user profile

what's the reason of this?

**Comment by skygragon** [comment]
@QiangZiBro sound like a networking issue, see #94
