### ISSUE TITLE
Feature request: save password locally in an encrypted file.

### ISSUE THREAD

**Issue by 9527KGG** [skygragon/leetcode-cli#123]
Current cli frequently asks for name/password. I understand this is leetcode website issue. Basically websit just kicks me out.

I am wondering: is it possible to save password locally in an encrypted file? So when web asks for password, cli uses the password info from the local file. So I didn't need type name/password again and again.

Thanks.

**Comment by 9527KKK** [comment]
On website, generally, browser can remember the password. So I don't need type the password, which is OK.
Current cli cannot remember the password. So it's very annoying to type password again and again.

**Comment by 9527KKK** [comment]
Click "Close and comment" by mistake :)

**Comment by sfdye** [comment]
You can use the chrome cookie plugin:
https://github.com/skygragon/leetcode-cli-plugins/blob/master/docs/cookie.chrome.md

**Comment by 9527KKK** [comment]
With the plugin, I hit

[DEBUG] running cookie.chrome.login
[DEBUG] running cookie.chrome.signin
[DEBUG] try to copy leetcode cookies from chrome ...
readline.js:1021
            throw err;
            ^

Error: Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.Chrome.getCookies (/usr/local/lib/node_modules/leetcode-cli/lib/plugins/cookie.chrome.js:132:17)
    at Plugin.plugin.signin (/usr/local/lib/node_modules/leetcode-cli/lib/plugins/cookie.chrome.js:160:6)
    at Plugin.plugin.login (/usr/local/lib/node_modules/leetcode-cli/lib/plugins/cookie.chrome.js:177:10)
    at Plugin.plugin.login (/usr/local/lib/node_modules/leetcode-cli/lib/plugins/cache.js:70:15)
    at /usr/local/lib/node_modules/leetcode-cli/lib/commands/user.js:47:12
    at /usr/local/lib/node_modules/leetcode-cli/node_modules/prompt/lib/prompt.js:336:32

sudo npm install sqlite3
sudo apt install sqlite3
do not help. 

What do I miss here? thanks.

**Comment by sfdye** [comment]
Try re-install leetcode-cli again and install the plugin?

**Comment by 9527KKK** [comment]
Are reinstall, the new error is:

[DEBUG] running cookie.chrome.login
[DEBUG] running cookie.chrome.signin
[DEBUG] try to copy leetcode cookies from chrome ...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_CANTOPEN: unable to open database file

Any suggestion? Thanks.

**Comment by 9527KKK** [comment]
I'm using ubuntu 18 LTS. Thanks.

**Comment by 9527KKK** [comment]
I figured it out. I am using chromium instead of google chrome.
You may close the ticket. thanks.
It would be great if both google chrome and chromium could be supported.
