### ISSUE TITLE
No source code is downloaded

### ISSUE THREAD

**Issue by 9527KGG** [skygragon/leetcode-cli#126]
### Problem Summary

The downloaded template does not have code.

### How to reproduce
1. which command failed, what parameters used

leetcode show 1 -g -x -l cpp

2. actual/expected output

Actual: 
[1] Two Sum  

https://leetcode.com/problems/two-sum/description/

Tags:   algorithms 

Langs:  c   cpp   csharp   golang   java   javascript   kotlin   python   python3   ruby   scala   swift 

* algorithms
* Easy (38.97%)
* Source Code:       1.two-sum.2.cpp
* Total Accepted:    1.1M
* Total Submissions: 2.9M
* Testcase Example:  '[2,7,11,15]\n9'

Given an array of integers, return indices of the two numbers such that they add up to a specific target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

Example:

Given nums = [2, 7, 11, 15], target = 9,

Because nums[0] + nums[1] = 2 + 7 = 9,
return [0, 1].

Expected:
cpp code template should be downloaded 

_[1] Two Sum  

https://leetcode.com/problems/two-sum/description/

Tags:   algorithms 

Langs:  c   cpp   csharp   golang   java   javascript   kotlin   python   python3   ruby   scala   swift 

* algorithms
* Easy (38.97%)
* Source Code:       1.two-sum.2.cpp
* Total Accepted:    1.1M
* Total Submissions: 2.9M
* Testcase Example:  '[2,7,11,15]\n9'

Given an array of integers, return indices of the two numbers such that they add up to a specific target.

You may assume that each input would have exactly one solution, and you may not use the same element twice.

Example:

Given nums = [2, 7, 11, 15], target = 9,

Because nums[0] + nums[1] = 2 + 7 = 9,
return [0, 1].

class Solution {
public:
    vector<int> twoSum(vector<int>& nums, int target) {
        
    }
};_

3. if possible, run command with "-vv" will give more outputs of the HTTP data, do REMEMBER to delete your cookies before paste here!!

### Environment

[Environment]
Node                 v8.12.0
OS                   linux 4.15.0-36-generic
Cache                /home/xxx/.lc/cache
Config               /home/xxx/.lc/config.json

[Configuration]
autologin            {"enable":false,"retry":2}
code                 {"editor":"vim","lang":"cpp"}
color                {"enable":true,"theme":"default"}
icon                 {"theme":""}
network              {"concurrency":10}

[Themes]
Colors               blue,dark,default,molokai,orange,pink,solarized,solarized.light
Icons                ascii,default,win7

[Plugins]
solution.discuss     2018.04.14
company              2017.12.18
cache                default
retry                default
cookie.chrome        2018.05.30
leetcode             default

- leetcode-cli version: 318983cd7f79bf27e1e7f64927204e91445fc653

- OS version: ubuntu lts 18
- Node version: 8.12.0
- Npm version: 6.4.1

**Comment by skygragon** [comment]
@9527KGG in your paste above, here is "Source Code:   1.two-sum.2.cpp", you mean there is no code generated in that file?

**Comment by kgfly** [comment]
The issue no longer repro.
