### ISSUE TITLE
leetcode stat 

### ISSUE THREAD

**Issue by kadisi** [skygragon/leetcode-cli#129]
### Problem Summary

When I exec `leetcode submit someQuection.go ` at different times on the two machines,  all the submit are accepted,  but when i exec `leetcode stat -c` command, it shows different data.
for example ：
when i exec `leetcode submit 852.peak-index-in-a-mountain-array.go` on machines A at Thursday， it finally accepted. and i exec  `leetcode stat -c` on machines B at Friday , i show that there is no submit at Thursday.

does `leetcode stat -c` only show local cache?

### Environment

- leetcode-cli version:

- OS version:
- Node version:
- Npm version:

**Comment by skygragon** [comment]
@kadisi yes, for now it's totally local saved ...
