### ISSUE TITLE
leetcode show 515 -gx

### ISSUE THREAD

**Issue by cosmozhang** [skygragon/leetcode-cli#131]
The generated file 515 is not 515, but another question,
[515.find-largest-value-in-each-tree-row.0.py.txt](https://github.com/skygragon/leetcode-cli/files/2551596/515.find-largest-value-in-each-tree-row.0.py.txt)

### Environment

- leetcode-cli version:

- OS version:
- Node version:
- Npm version:

**Comment by skygragon** [comment]
@cosmozhang for leetcode, 515 is "Find Largest Value in Each Tree Row". Could you please elaborate your problem?

**Comment by cosmozhang** [comment]
If you open the .txt file I uploaded, you will find the template is for "threeSumClosest".

**Comment by skygragon** [comment]
Did it occur randomly? sound like a invalid cache. could you remove 515's cache and try again?
```
$ leetcode cache -d 515
```

**Comment by cosmozhang** [comment]
After removing the cache, it works.
