### ISSUE TITLE
Pull detail msg for runtime error

### ISSUE THREAD

**Issue by gynet** [skygragon/leetcode-cli#14]
When a submission got runtime error, there is no detail message return to the console. It would nice if leetcode-cli can pull the detail error msg.

**Comment by skygragon** [comment]
could you give a user case that I can dig into?

**Comment by gynet** [comment]
Use case: 

https://leetcode.com/problems/longest-increasing-subsequence/

If you test with following code: 
--------------------------------------------------------
public class Solution {
    public int lengthOfLIS(int[] nums) {
        int [] dp = new int [nums.length+1];
        if (nums.length == 0){
            return 0;
        }
        int size = 1;
        dp[1] = nums[0]; 
        for (int i = 0; i < nums.length; i++){
            int k = Arrays.binarySearch(dp, 1, i, nums[i]);
            if (k == size + 1){
                size++;
            }
            if (k < 0){
                k = -( k + 1);
            }
            dp[k] = nums[i]; 
        }
        return size;
    }
------------------------------------------------

**Comment by gynet** [comment]
with latest build, still did not see runtime error in cli, so currently I have to login to web for debugging.

Test case:

leetcode test zigzag-conversion.java -t '[3,9,20,null,null,15,7]'

public class Solution {
public List<List> zigzagLevelOrder(TreeNode root) {
List<List> res = new ArrayList();
dfs(root, 0, res);
return res;
}

public void dfs (TreeNode node, Integer level, List<List<Integer>> res ){
    if (node == null){
        return;
    }
    List<Integer> levelNodes = res.get(level);
    if (res.get(level) == null){
        levelNodes = new ArrayList();
        res.add(levelNodes);
    }
    
    //right; left
    if (level % 2 == 1){
        levelNodes.add(0, node.val);
    }
    else {
        levelNodes.add(node.val);
    }
    dfs(node.left, level+1, res);
    dfs(node.right, level+1, res);
}
}

**Comment by skygragon** [comment]
hmm..this source code should aim at binary-tree-zigzag-level-order-traversal.java, not zigzag-conversion.java, right?

Following is what I run using this code:
```
⭠master leetcode-cli# leetcode test binary-tree-zigzag-level-order-traversal.java -t '[3,9,20,null,null,15,7]'

Input data:
[3,9,20,null,null,15,7]

Your
    ✘ Runtime Error
    ✘ runtime: N/A
    ✘ output:
    ✘ error: Line 12: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0


Expected
    ✔ runtime: 0 ms
    ✔ answer: [[3],[20,9],[15,7]]
    ✔ output:
```

Do you try to update the global version of leetcode-cli on your machine? something like:
```
leetcode-cli$ git pull --rebase original master
leetcode-cli$ sudo npm install -g .
```

**Comment by gynet** [comment]
Oh, your are right, my bad, linked to a wrong source file, currently it's working as excepted. Sorry for bring the confusion.

**Comment by gynet** [comment]
Please close it
