### ISSUE TITLE
[Feature Request] support rust lang

### ISSUE THREAD

**Issue by yifeikong** [skygragon/leetcode-cli#155]
### Problem Summary
Invalid values:
  Argument: l, Given: "rust", Choices: "bash", "c", "cpp", "csharp", "golang", "java", "javascript", "kotlin", "mysql", "python", "python3", "ruby", "scala", "swift"

**Comment by skygragon** [comment]
rust support has been merged while not released yet. You could try latest dev version via `npm install -g skygragon/leetcode-cli`

**Comment by skygragon** [comment]
see #142
