### ISSUE TITLE
Why the latest question cannot be downloaded?

### ISSUE THREAD

**Issue by 9527KGG** [skygragon/leetcode-cli#171]
### Problem Summary

Not sure if it's a bug or by design. Anyway,

The download latest question cannot be downloaded

### How to reproduce

leetcode show 1100 -gx -l python3
prompted:
[ERROR] Problem not found!

### Environment

- leetcode-cli version:

- OS version: Ubuntu 18 LTS
- Node version:
- Npm version:

**Comment by 9527KGG** [comment]
On  the hand, 

leetcode show 900 -gx -l python3

works normally.

**Comment by lebeier** [comment]
The problem seems to be locked, do you have premium account?

**Comment by 9527KGG** [comment]
I do have premium account and I just tried an non premium question eg, 1125

"leetcode show 1042 -gx -l python3", which prompts the same error
_[ERROR] Problem not found!_

Moreover, I just and reinstall with 

rm -fr ~/.nvm 
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
$ source ~/.bashrc
nvm install --lts
npm install -g leetcode-cli

Current version is 2.6.1

May you please take a look what's wrong here?

**Comment by 9527KGG** [comment]
I noticed that all questions after 102X cannot be downloded.

**Comment by ketankr9** [comment]
Try to logout then re-login and see if the new questions are downloaded 
``` leetcode user -L ``` followed by ```leetcode user -l```

This is how I update the question list. Right now it is showing up to 1143.

**Comment by 9527KGG** [comment]
working now. will keep an eye on it.

Thanks
