### ISSUE TITLE
test stuck in "Waiting for judge result"

### ISSUE THREAD

**Issue by 6uipoeib** [skygragon/leetcode-cli#187]
### Problem Summary
Test stucks in "Waiting for judge result"

### How to reproduce
`leetcode-cli test 93.restore-ip-addresses.py`

when running -vv:
`[TRACE] REQUEST %s make request https://leetcode.com/submissions/detail/undefined/check/
`
Somehow the $id is 'undefined'

### Environment
- leetcode-cli version: 2.6.2
- OS version: Mac OSX Catalina
- Node version: v10.6.0
- Npm version: 6.4.1

**Comment by liabixiaoxin** [comment]
Same issue here.

**Comment by waste-didi** [comment]
same here for 2 days.
tried reinstalling, then the status got stuck in "downloading plugins from ..."

**Comment by hupei1991** [comment]
same issue...

**Comment by waste-didi** [comment]
> same here for 2 days.
> tried reinstalling, then the status got stuck in "downloading plugins from ..."

Tried again. The installation went through but not the testing process.

**Comment by waste-didi** [comment]
Logs seem to be in a loop
`[TRACE] REQUEST %s reading response's body
[TRACE] REQUEST %s finish init function https://leetcode.com/submissions/detail/undefined/check/
[TRACE] REQUEST %s response end https://leetcode.com/submissions/detail/undefined/check/ 200 { date: 'Thu, 10 Oct 2019 21:58:43 GMT',
  'content-type': 'application/json',
  'content-length': '20',
  connection: 'close',
  'set-cookie':
   [ '__cfduid=df2982c7d2f0e1208cacdde521a15adb51570744723; expires=Fri, 09-Oct-20 21:58:43 GMT; path=/; domain=.leetcode.com; HttpOnly',
     'csrftoken=pjyxI69YKYRN1swg46pYClC90Y7e8L43IL5oVR2Uf1kb7rnINYNlrUnlNEY98dlg; expires=Thu, 08 Oct 2020 21:58:43 GMT; Max-Age=31449600; Path=/; SameSite=Lax; Secure' ],
  vary: 'Cookie',
  'x-frame-options': 'SAMEORIGIN',
  'cf-cache-status': 'DYNAMIC',
  'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
  'x-content-type-options': 'nosniff',
  'expect-ct':
   'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  server: 'cloudflare',
  'cf-ray': '523bdb7c4c602814-SJC' }
[TRACE] REQUEST %s end event https://leetcode.com/submissions/detail/undefined/check/
[TRACE] REQUEST %s has body https://leetcode.com/submissions/detail/undefined/check/ 20
[TRACE] REQUEST %s emitting complete https://leetcode.com/submissions/detail/undefined/check/
⠋ Waiting for judge result[TRACE] REQUEST %s { url: 'https://leetcode.com/submissions/detail/undefined/check/',
  headers:
   { Cookie:
      <hidden>,
     'X-CSRFToken':
      <hidden>,
     'X-Requested-With': 'XMLHttpRequest',
     Origin: 'https://leetcode.com',
     Referer: 'https://leetcode.com/problems/decode-string/description/' },
  body: null,
  method: 'GET',
  json: false,
  _delay: 1,
  callback: [Function] }
[TRACE] REQUEST %s make request https://leetcode.com/submissions/detail/undefined/check/
⠴ Waiting for judge result^C`

**Comment by waste-didi** [comment]
Updated to this version and it worked well.
[https://github.com/leetcode-tools/leetcode-cli](https://github.com/leetcode-tools/leetcode-cli)

**Comment by kgfly** [comment]
Ubuntu Linux has this issue too.

**Comment by coppercash** [comment]
same

**Comment by 6uipoeib** [comment]
I think leetcode has changed it's API. 

now 
https://leetcode.com/problems/restore-ip-addresses/interpret_solution/
doesn't return `interpret_expected_id` any more
e.g.
```
{
  "interpret_id": "runcode_1571376917.5742006_NNLB0UvvU0",
  "test_case": "\"25525511135\""
}
```

but 
https://leetcode.com/submissions/detail/runcode_1571376496.0609925_aBW6xwrmEM/check/ returns extra "expected" data
e.g.
```
{
    "status_code": 10,
    "lang": "python3",
    "run_success": true,
    "status_runtime": "72 ms",
    "memory": 13816000,
    "code_answer": [
        "[\"25525511135\"]"
    ],
    "code_output": [],
    "expected_status_code": 10,
    "expected_lang": "cpp",
    "expected_run_success": true,
    "expected_status_runtime": "0",
    "expected_memory": 8276000,
    "expected_code_answer": [
        "[\"255.255.11.135\",\"255.255.111.35\"]"
    ],
    "expected_code_output": [],
    "correct_answer": false,
    "total_correct": null,
    "total_testcases": null,
    "runtime_percentile": null,
    "status_memory": "13.8 MB",
    "memory_percentile": null,
    "pretty_lang": "Python3",
    "submission_id": "runcode_1571376496.0609925_aBW6xwrmEM",
    "status_msg": "Accepted",
    "state": "SUCCESS"
}
```

**Comment by 6uipoeib** [comment]
@akanarika is right. This repo is no longer maintained (https://github.com/skygragon/leetcode-cli/issues/181). We can move on to https://github.com/leetcode-tools/leetcode-cli

**Comment by Layamon** [comment]
Same issue

**Comment by HwangTaehyun** [comment]
#214 PR fix this issue.

**Comment by HwangTaehyun** [comment]
**Environment**
- leetcode-cli version: 2.6.2
- Node version: v10.6.0
- Npm version: 6.9.0
- OS version: Mac OS Catalina

**You can install it using this command.** 
- npm i -g HwangTaehyun/leetcode-cli

**Comment by kgfly** [comment]
@HwangTaehyun ,where to get latest release? The last release is 2.6.2 on 9/28/19. Thanks.

**Comment by HwangTaehyun** [comment]
@9527KGG I think this project is not managed more. I fix this problem in my fork project.
You can use my fork project temporarily.
```bash
npm install -g HwangTaeHyun/leetcode-cli
```

**Comment by devstefancho** [comment]
@HwangTaehyun thanks it works, I hope your PR will be merged
