### ISSUE TITLE
If a user login the leetcode website, and then use the cli to access locked problem, it will show "ERROR: failed to load locked problem!"

### ISSUE THREAD

**Issue by gynet** [skygragon/leetcode-cli#21]
If a user login the leetcode website, and then use the cli to access locked problem, it will show "ERROR: failed to load locked problem!"

**Comment by skygragon** [comment]
That because your cli session is expired as soon as you login on the website, see https://github.com/skygragon/leetcode-cli/blob/master/doc/advanced.md#auto-login

**Comment by skygragon** [comment]
Hey @gynet, can we close this ticket now?

**Comment by gynet** [comment]
Yes
