### ISSUE TITLE
Session keeps on getting expired with message 'ERROR: session expired, please login again'

### ISSUE THREAD

**Issue by ravioactive** [skygragon/leetcode-cli#24]
Installed it on bash on osX.
After logging in with `lc user -l`, the command succeeds with a `Successfully logged as <username>` message.
But the session expires almost immediately. Any other command fails with a `ERROR: session expired, please login again` message.
Logging in again does not change the behavior.

**Comment by skygragon** [comment]
please try the latest release 0.7.0 to see if this issue still exists?

**Comment by ravioactive** [comment]
I ran `npm uninstall leetcode-cli` yesterday and installed this again. But it did not fix the issue. Should I do this again or is there a different procedure to get the latest version?

**Comment by ravioactive** [comment]
Its working now, thanks!
