### ISSUE TITLE
List questions by company tag?

### ISSUE THREAD

**Issue by qqldd** [skygragon/leetcode-cli#25]
Can we add an option to list questions by company tag?

For example:
`leetcode list -c google`

List all google questions.

**Comment by skygragon** [comment]
Unfortunately the company info doesn't come up with the lis query, which means we have to crawl over all the questions to collect those info... I was thinking of provide a new command to fully download all questions once for all, just like what career-cli does.

**Comment by skygragon** [comment]
by the way I have already tested this kind of fully download in https://github.com/skygragon/Q.mobile, the good thing is currently we only have ~500 questions on leetcode, so this download would cost too much time thus might be acceptable. Any ideas?

**Comment by yefeiw** [comment]
Hi Sky,  I wonder if providing page number and company name we will be able to do it?  I am very interested in this feature as well.

**Comment by skygragon** [comment]
BTW, for those non-premium users, feel free to try the 'company' plugin in https://github.com/skygragon/leetcode-cli-plugins

This feature need the latest commits in leetcode-cli.

**Comment by cindywxw** [comment]
This function seems really great, thanks! 
This may be a silly question, but how to update leetcode-cli with the latest commits?

**Comment by skygragon** [comment]
@cindywxw 2.0.0 is released with plugin support, please try `npm install -g leetcode-cli@latest`

**Comment by cindywxw** [comment]
@skygragon It's really great. Thanks!

**Comment by kedarmp** [comment]
@skygragon Does the company plugin mean that non premium users can view those company specific lists?

**Comment by skygragon** [comment]
@kedarmp yep but those company info is collected from internet, so it's not 100% accurate.
