### ISSUE TITLE
'leetcode show' gives message " ERROR: failed to load problem!"

### ISSUE THREAD

**Issue by jiayi73** [skygragon/leetcode-cli#26]
Having trouble loading problem with 'leetcode show'. Also, is there a debug switch for more logging? I'd like to provide more information but I don't know how.

System Environment:
npm@4.5.0
leetcode-cli@0.7.0

**Comment by boylee1111** [comment]
I had the same issue with 'leetcode show'. How did you resolve it? If I run 'leetcode sho with verbose log, it print:

loading from all.json
ERROR: failed to load problem!
