### ISSUE TITLE
'leetcode show' gives message " ERROR: failed to load problem!"

### ISSUE THREAD

**Issue by boylee1111** [skygragon/leetcode-cli#27]
I noticed one guy had the same issue here. It might be network issue, I could access web link well. And I tried changing network still the same.

> System Environment:
> npm@4.5.0
> leetcode-cli@0.7.0

And if I run it with verbose log, it prints below:

> loading from all.json
> ERROR: failed to load problem!

Any idea how could I resolve this?

**Comment by skygragon** [comment]
Thanks for reminding me this break! Seems leetcode.com has changed the html recently, working on it...

**Comment by skygragon** [comment]
@boylee1111 the fix is merged. Please help to check if there other issue exist, e.g. test/submit.

**Comment by boylee1111** [comment]
@skygragon great! works! Thanks a lot 👍
