### ISSUE TITLE
The color rending and icon on Windows Terminal is Wired 

### ISSUE THREAD

**Issue by gynet** [skygragon/leetcode-cli#35]
Tried cli on windows a while ago, and it was working, but I tried it today, it just became wired. 
![untitled](https://cloud.githubusercontent.com/assets/2174522/26734995/01d81f84-4775-11e7-9c0d-42234669a82c.png)

**Comment by gynet** [comment]
Everyone is using macbook?  逃....

**Comment by skygragon** [comment]
I would encourage you to use linux/mac instead because windows will be no longer supported on the long term roadmap. The terminals on windows are quite limited by Microsoft OS with only poor functionalities provided, which means we can't maintain the same user experience as we already enjoyed on linux/mac.

**Comment by gynet** [comment]
I agree that the terminals on Windows have many legacy problems, but there are still many people have to use Windows because of many reasons, e.g Working required. Also, I think MSFT is trying to improve the user experience of their terminals as well: 

https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/
https://github.com/PowerShell/PowerShell/issues/2381

So it would good for leetcode-cli to keep minimal support for Windows.

**Comment by skygragon** [comment]
@gynet The latest commit should address the coloring issue on windows, please try it out. The other thing is about unicode charset on windows, later there will be some commits for that. Basically the idea is for windows we might degrade some features but let the basic functionalities work a bit.

**Comment by gynet** [comment]
Thanks, verified it works!
