### ISSUE TITLE
Feature Request: Add a command to fetch top discussion post

### ISSUE THREAD

**Issue by gynet** [skygragon/leetcode-cli#36]
It would be nice to add the feature to be able to fetch the top discussion post into cli.

**Comment by skygragon** [comment]
Actually it was purposely omit in the original backlog because it's kind of "cheating" to see the solution. Introducing it in cli will make this cheating much cheaper and make you easily to give up thinking.

**Comment by gynet** [comment]
I understand your point, but I would say that's case by case and depends on humanity, if people want to see the solution without deep thinking, they will "cheat" anyway by using a browser....
It would be still good to have such functionality for people who just want focus on the cli without any interaction with a browser, and I think it's the overall goal of a cli program.

**Comment by gynet** [comment]
Maybe it would be nice to add it as a way not so easy to get the solution, or add a timer to check the time stamp of the template file?

**Comment by skygragon** [comment]
I'm thinking to introduce this kind of feature as a plugin, thus users who need it could install it on demand. See https://github.com/skygragon/leetcode-cli-plugins for more details.

**Comment by skygragon** [comment]
@gynet please try release 2.0.1 and install solution.discuss plugin in https://github.com/skygragon/leetcode-cli-plugins/
