### ISSUE TITLE
ERROR: failed to load locked problem!

### ISSUE THREAD

**Issue by gynet** [skygragon/leetcode-cli#37]
It shows "ERROR: failed to load locked problem!" even I am a premium user.

**Comment by skygragon** [comment]
I don't have paid account in hand, but can you try again with latest commit code?

**Comment by gynet** [comment]
Still having the same problem. Using version: 0.9.0-4e1469c

**Comment by gynet** [comment]
Oh, it looks got fixed after I removing the cache.
