### ISSUE TITLE
Question Description is Not Shown Up

### ISSUE THREAD

**Issue by gynet** [skygragon/leetcode-cli#44]
### Problem Summary
Question description is not shown up. 
### How to reproduce

leetcode show 372

### Environment

057ab1fccbc589f482aa3256c18a94a0cb50a318

- leetcode-cli version:

- OS version:
- Node version:
- Npm version:

**Comment by skygragon** [comment]
try removing cache: `rm ~/.lc/super-pow.json`?

**Comment by gynet** [comment]
yes. it came back after removing cache ....

**Comment by skygragon** [comment]
related to #45
