### ISSUE TITLE
How to delete it cleanly?

### ISSUE THREAD

**Issue by henryzbw** [skygragon/leetcode-cli#47]
Hello, I don't know how to do that? Can you provide a guide?

**Comment by skygragon** [comment]
By "delete it" do you mean uninstall leetcode-cli from your computer?

**Comment by henryzbw** [comment]
yes~

**Comment by skygragon** [comment]
try

```
npm uninstall -g leetcode-cli
```

**Comment by henryzbw** [comment]
It works, thanks:)

**Comment by skygragon** [comment]
@henryzbw may I ask why do you want uninstall it? I will help us some to improve the tool.

**Comment by henryzbw** [comment]
I seldom used it, so I just want to uninstall it.
