### ISSUE TITLE
Is it possible to refresh the list after login another computer?

### ISSUE THREAD

**Issue by fuermosi777** [skygragon/leetcode-cli#51]
I turned on "ALWAYS_LOGIN" for both my computers. When I submit from one of the computer and run "leetcode list" in another one, it still keeps the old list (without the submitted one). I wonder if it's possible to refresh the list instead of using cache? Or do I have to run `lc user -l` each time?

Thanks!!

**Comment by skygragon** [comment]
Yes, it would be better to clean the user cache (e.g. question list) whenever auto login detected a session expired. Will fix it in next release I hope.

**Comment by fuermosi777** [comment]
Thank you for the reply

**Comment by skygragon** [comment]
Let's make this ticket open for tracking purpose.

**Comment by skygragon** [comment]
@fuermosi777 which leetcode-cli version do you use? Seems the latest release should have fixed this issue?

**Comment by skygragon** [comment]
please try release 1.0.0
