### ISSUE TITLE
Add the optional parameter `keyword` for the `submit` and `test` commands

### ISSUE THREAD

**Issue by idennydeng** [skygragon/leetcode-cli#52]
Add the optional parameter `keyword` for the `submit` and `test` commands, for command:
```
  submit <filename> [keyword]  submit final solution to leetcode
  test <filename> [keyword]    send solution to leetcode and run test
```

**Comment by skygragon** [comment]
@idennydeng would you share more context when the keyword is required?

**Comment by skygragon** [comment]
closed stale ticket for now, feel free to reopen it if issue still occurs.
