### ISSUE TITLE
[Feature Request] support other types of questions like database/shell, etc

### ISSUE THREAD

**Issue by NoahDragon** [skygragon/leetcode-cli#54]
The SQL problems seem couldn't be accessed, by using the following command:

```
leetcode show 175
```

Here is the link for 175 problem: https://leetcode.com/problems/combine-two-tables/#/description

Is there any plan to support this?

Thanks for creating this great tool.

**Comment by skygragon** [comment]
Currently we don't support other problems beyond algorithms, while it's a good idea to support other problem sets as well. We should put this in our backlog while I'm not sure any ETA on it...

**Comment by skygragon** [comment]
feel free to try release 1.0.0

**Comment by NoahDragon** [comment]
@skygragon Thank you, I will have a try.

**Comment by NoahDragon** [comment]
@skygragon works like a charm. Thanks!
