### ISSUE TITLE
test issue and submit beats ratio bugs

### ISSUE THREAD

**Issue by danche354** [skygragon/leetcode-cli#57]
### Problem Summary

1. When use `leetcode test ./.cpp -t testcase`, it occurs error adding quotation marks on testcase, the `command documentations` may need changed :).
2. How to use interactive command `-i` in test occasion, when I use `leetcode test ./.cpp -i` in Win10, I don't know what to do next and I tried some input, cmd didn't response.
3. Why every time I submit, it gives me `beats 100% of cpp submissions`? Actually it didn't.
### Environment

- leetcode-cli version:

- Win10 professional version:
- Node version: v8.1.4
- Npm version: 5.0.3

**Comment by skygragon** [comment]
@danche354 Which version of leetcode-cli are u using?

1. please share me the testcase you failed with? basically you can copy/paste the testcase example display in 'show' command.
2. on linux we use ctrl-D to send EOF event, while seems windows can't recognize this event thus failed to end. Will fix it later. 
3. I meet the same problem recently, will look into it.

Thanks for reporting this.

**Comment by danche354** [comment]
@skygragon Thanks for your reply! The 1st question is solved as I used `"` rather than `'`. I think it will be better to provide a command `pick` for pick an random one.

**Comment by skygragon** [comment]
feel free to try release 1.0.0

**Comment by skygragon** [comment]
#58 is create for random pick one.
