### ISSUE TITLE
`leetcode show -gx` not work anymore

### ISSUE THREAD

**Issue by Wilbeibi** [skygragon/leetcode-cli#60]
### Problem Summary

`leetcode show -gx num`  not work anymore

### How to reproduce

Let's say `leetcode show -gx -l python 76`, it generate template of another problem.
Maybe because leetcode website did some changes.

### Environment

- leetcode-cli version:

- OS version:  MacOS 10.11
- Node version: 5.12
- Npm version: 5.3

**Comment by skygragon** [comment]
@Wilbeibi could you share your output and leetcode-cli version? I just tested and it generated 76.minimum-window-substring.py for me.

**Comment by Wilbeibi** [comment]
The name is correct, but the description (in comment) and the template code has some issue (another problem's template code):
Generated version:
```
#
# [72] Edit Distance
#
# https://leetcode.com/problems/edit-distance
#
# algorithms
# Hard (31.61%)
# Total Accepted:    
# Total Submissions: 
# Testcase Example:  ''
#
# 
#
"""
Definition of TreeNode:
class TreeNode:
    def __init__(self, val):
        self.val = val
        self.left, self.right = None, None
"""


class Solution:
    """
    @param inorder : A list of integers that inorder traversal of a tree
    @param postorder : A list of integers that postorder traversal of a tree
    @return : Root of a tree
    """
    def buildTree(self, inorder, postorder):
        # write your code here
        
```
 version: 2.0.1-b086bf7


BTW: 多谢这个工具，让我可以上班时候摸鱼刷题~~

**Comment by skygragon** [comment]
我猜你是不是用了lintcode插件？所以生成的是lintcode 72题？如果是的话需要把lintcode插件disable：
```
$ leetcode plugin -d lintcode
```

**Comment by Wilbeibi** [comment]
几个小时前是装了，刚才检查发现说 plugin not found。看样子是 lintcode 插件的问题。我把 cache 清了试试，多谢~~
