### ISSUE TITLE
Password showing as plaintext when logging in

### ISSUE THREAD

**Issue by Andrew-peng** [skygragon/leetcode-cli#61]
Hi I think this is a great tool, but for security I think when the user inputs a password it should not be shown as plaintext. Currently on my computer when I login my password is shown as plaintext using Git Bash on Windows. Maybe have it like this instead?

```bash
username: johndoe
password: *****************
```

or just not show the password

**Comment by skygragon** [comment]
It SHOULD hide the password, let me find a windows and check it.

**Comment by skygragon** [comment]
I tried on win7 with leetcode-cli@2.0.2, the password is hide on both builtin cmd and git bash.
```
C:\Users\root>npm install leetcode-cli@latest
......
C:\Users\root>leetcode version
2.0.2
C:\Users\root>leetcode user -l
login: nobody
pass:
[ERROR] invalid password? [0]
```

**Comment by Andrew-peng** [comment]
It looks like its being shown as plaintext on Windows 10 with version `2.0.2-f44f54b`

**Comment by skygragon** [comment]
Currently I don't have win10 around, will look into it when I get one.

**Comment by skygragon** [comment]
@Andrew-peng I think the problem is from git-bash only, please try git CMD or powershell instead.
