### ISSUE TITLE
question about test with python3

### ISSUE THREAD

**Issue by z0re** [skygragon/leetcode-cli#65]
### Problem Summary

When I have ran the 
leetcode test ./3.longest-substring-without-repeating-characters.py -i 'abc'

it shows:
  ✘ Runtime Error
  ✘ runtime: N/A
  ✘ answer: 
  ✘ stdout: ''
  ✘ error: Line 66: ValueError: No JSON object could be decoded

### How to reproduce

try any cpp/python with leetcode test ./[file] should reproduce the problem
### Environment

- leetcode-cli version:

- OS version:ubuntu 16.04
- Node version: 4.2.6
- Npm version:3.5.2

**Comment by skygragon** [comment]
`-i` is used to read testcase from stdin, for your case please try use `-t` instead?
```
leetcode test ./3.longest-substring-without-repeating-characters.py -t 'abc'
```

**Comment by shihan9** [comment]
i suggest adding a flag `-l` for `leetcode submit` to specify the language of file we submit or make `.lcconfig` visible to `leetcode submit`.

p.s. leetcode-cli will set the python3 file with extention ".py3" which is pretty rare in python world. vim also doesn't regard ".py3" as a python file by default.

**Comment by skygragon** [comment]
@shihan9 there is another python3 thread: #55
