### ISSUE TITLE
show with more options ?

### ISSUE THREAD

**Issue by diabloevagto** [skygragon/leetcode-cli#67]
can support more option

1. submission option `-o`
2. list option `-q` 
3. randomly problem without ac

thanks

**Comment by skygragon** [comment]
@diabloevagto could you elaborate the details of the 3 items above?

**Comment by diabloevagto** [comment]
can i replay by Chinese ?

當想練習新的題目時會用 show 產生新的題目，希望 show 指令可以新增一些其他 options

1. submission 的 -o，因為我同時使用多個語言，會希望能夠再產生的時候直接分到 js 或 cpp 的資料夾
2. list 的 -q，可以直接指定難度
3. 能夠剔除已經 AC 完成過的，例如我已經完成 [001] 那在隨機產生可以跳過 [001]

**Comment by skygragon** [comment]
item 3 should be addressed already as far as I know.

**Comment by skygragon** [comment]
@diabloevagto please try the latest commits to see if that fits your desire?
```
$ npm install -g skygragon/leetcode-cli
```

**Comment by diabloevagto** [comment]
thanks, i will feedback tonight

**Comment by diabloevagto** [comment]
> npm install -g skygragon/leetcode-cli
prefect 

but 
> npm install -g leetcode-cli
no feature

what they different ?

**Comment by skygragon** [comment]
@diabloevagto yes, the latter way is installing a stable release that didn't include those fresh commits yet.
