### ISSUE TITLE
leetcode-cli installed successfully， but command ''leetcode" doesn't work 

### ISSUE THREAD

**Issue by GEeKkk** [skygragon/leetcode-cli#69]
### Problem Summary

leetcode: command not found
### Environment

- leetcode-cli version:  2.0.2

- OS version:  ubuntu 17.10
- Node version:  v6.11.4
- Npm version: 3.10.10

**Comment by skygragon** [comment]
never tested on ubuntu 17.10 yet, let me try that.

**Comment by skygragon** [comment]
I guess you didn't install leetcode-cli globally? e.g. `npm install -g leetcode-cli`

**Comment by raghumaddali** [comment]
It's actually an issue on Windows 10 too. Worked fine on Mac though.

**Comment by skygragon** [comment]
Tried on ubuntu 17.10, no error hit...
```
root@d5deb9a3ea40:/# cat /etc/issue
Ubuntu 17.10 \n \l
root@d5deb9a3ea40:/# node -v
v6.11.4
root@d5deb9a3ea40:/# npm -v
3.5.2
root@d5deb9a3ea40:/# npm install -g leetcode-cli
.......
root@d5deb9a3ea40:/# leetcode version
2.0.3
```

**Comment by skygragon** [comment]
@raghumaddali tasted on win10, everything seems ok.
```
C:\Users\root>npm install skygragon/leetcode-cli

C:\Users\root>leetcode version -v
 _           _                  _
| |         | |                | |
| | ___  ___| |_  ___  ___   __| | ___
| |/ _ \/ _ \ __|/ __|/ _ \ / _` |/ _ \
| |  __/  __/ |_  (__| (_) | (_| |  __/
|_|\___|\___|\__|\___|\___/ \__,_|\___|  CLI v2.1.1

[Environment]
Node                 v8.9.3
OS                   win32 10.0.15063
Cache                C:\Users\root\.lc
Config               C:\Users\root\.lcconfig
```

**Comment by skygragon** [comment]
try reinstall a newer version of npm, I guess your issue will be gone.

**Comment by Pyboon** [comment]
![_20180117095103](https://user-images.githubusercontent.com/7457094/35021512-320ed778-fb6c-11e7-9c26-56d16c355d9b.png)
on ubuntu 16.04 LTS, I have the issue in the picture ,why?

**Comment by skygragon** [comment]
@Pyboon try to run npm without sudo?

**Comment by Pyboon** [comment]
![1](https://user-images.githubusercontent.com/7457094/35032819-4efc0e78-fba3-11e7-91d5-ea7fb2429034.png)
![2](https://user-images.githubusercontent.com/7457094/35032820-4f2fad46-fba3-11e7-9a8a-42eea55b35ba.png)
as seen in the pictures above, I have tried the whole process accroding to your doc, but still fail

**Comment by skygragon** [comment]
@Pyboon I guess your npm working folders (e.g. /home/wzy/.npm/) are already messed up because previous "sudo npm install", which have marked your folders to owned by "root", not you ("wzy"). 

Please try following to make the folders owned by you again:
```
sudo chown -R $(whoami) ~/.npm
``` 
Then install again, do remember NOT use "sudo" this time:
```
npm install -g skygragon/leetcode-cli
```

Not sure if it would fix your problem, please let me know what you find out.

**Comment by Pyboon** [comment]
with your method, I have fixed the issue, thank you!

**Comment by Javaboiiii** [comment]
┌──(javaboii㉿kali)-[~/leetcode-cli]
└─$ leetcode version
[WARN] Installing missing plugins, might take a while ...
node:fs:1886
  binding.unlink(path);
          ^

Error: ENOENT: no such file or directory, unlink '/usr/local/lib/node_modules/leetcode-cli/lib/plugins/solution.discuss.js'
    at Object.unlinkSync (node:fs:1886:11)
    at file.rm (/usr/local/lib/node_modules/leetcode-cli/lib/file.js:83:13)
    at WriteStream.<anonymous> (/usr/local/lib/node_modules/leetcode-cli/lib/plugin.js:170:21)
    at WriteStream.emit (node:events:524:28)
    at emitCloseNT (node:internal/streams/destroy:147:10)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: '/usr/local/lib/node_modules/leetcode-cli/lib/plugins/solution.discuss.js'
}

Node.js v20.19.2

getting this can anyone help
