### ISSUE TITLE
use cookie from default browser

### ISSUE THREAD

**Issue by yhcharles** [skygragon/leetcode-cli#71]
Is it possible to use cookie of system default browser?
So that we can use leetcode client while keeping login status in the browser.

**Comment by wong2** [comment]
Nope, cookies are stored encrypted

**Comment by yhcharles** [comment]
I think that should be possible, as this package does:
https://www.npmjs.com/package/chrome-cookies

**Comment by skygragon** [comment]
sounds useful if workable for different version of chrome. Is there an alternative for firefox as well?

**Comment by yhcharles** [comment]
there is a python package works for Chrome and Firefox:
https://github.com/borisbabic/browser_cookie3

**Comment by skygragon** [comment]
@yhcharles please try to the latest leetcode-cli and cookie.chrome plugin. You might wanna check https://github.com/skygragon/leetcode-cli-plugins/blob/master/docs/cookie.chrome.md first.

```
$ npm install -g skygragon/leetcode-cli
$ leetcode-cli plugin -i cookie.chrome -v
```
If succeed, try to login leetcode.com in your chrome browser, wait a bit and login in leetcode-cli again. We are expecting that both sessions are all functional in the same time.

**Comment by yhcharles** [comment]
Good job! It works!
