### ISSUE TITLE
Some questions have no test cases

### ISSUE THREAD

**Issue by gynet** [skygragon/leetcode-cli#8]
[208] Implement Trie (Prefix Tree)

https://leetcode.com/problems/implement-trie-prefix-tree

* Medium (25.58%)
* Total Accepted:    50086
* Total Submissions: 195758
*** Testcase Example:  'search("a")'**

It will exception by using this example.

**Comment by skygragon** [comment]
@gynet could you plz check if this issue is resolved?

**Comment by gynet** [comment]
Checked already, it works fine now.
