### ISSUE TITLE
Select different sessions for same user

### ISSUE THREAD

**Issue by better365** [skygragon/leetcode-cli#81]
Can we support switching sessions in the cli? Thanks

**Comment by better365** [comment]
@skygragon Thanks for the quick turnaround. Can you show us how to switch sessions? Is it under user or somewhere else?

**Comment by skygragon** [comment]
```
$ npm install -g leetcode-cli
$ leetcode session -h
```
@better365 please let me know if there are bugs out there.

**Comment by better365** [comment]
@skygragon I just tried it today. It works fine. It will be more straightforward to change the description a little bit. Thanks!

leetcode session -e xxx  Enable session by ~~keyword~~ Id
leetcode session -d xxx  Delete session by ~~keyword~~ Id

**Comment by skygragon** [comment]
@better365 here keyword could be session id or session name, usually the session id is hard to remember thus we can give each session a meaningful name and use it directly in the command.

**Comment by better365** [comment]
@skygragon Thanks for your clarification. Maybe because my session are just numbers like 2017 or 2018, it doesn't work by name. 

What I tried is first ``` leecode session``` to get the session ID then use ```leetcode seesion -e session_id``` 

Anyhow, thanks for the great work.

**Comment by skygragon** [comment]
@better365 yeah, thanks for helping find this bug! feel free to try my fresh fix here:
```
$ npm install -g skygragon/leetcode-cli
```

**Comment by better365** [comment]
@skygragon 刚刚测试了一下，没有问题，名字 和iｄ都可以了，谢谢！
