### ISSUE TITLE
Missing No.742 & 758 in list

### ISSUE THREAD

**Issue by shaodan** [skygragon/leetcode-cli#82]
### Problem Summary

Problem 742 is listed as No.743, (No.742 is skipped)
Problem 743 is listed as No.744,
...
Problem 756 is listed as No.757,
Problem 757(newest problem) is listed as No.759 (No.758 is skipped)

leetcode show 742 got [ERROR] Problem not found! [0]

### How to reproduce

leetcode list
leetcode show 742

### Environment

- leetcode-cli version:

- OS version: Ubuntu 16.04
- Node version: v8.1.4
- Npm version: 5.4.2

![image](https://user-images.githubusercontent.com/495191/34564012-16d13676-f190-11e7-8bdc-000bbabe8a8e.png)
![image](https://user-images.githubusercontent.com/495191/34564035-2cd37902-f190-11e7-97ea-1cc3d6fbdc6e.png)
![image](https://user-images.githubusercontent.com/495191/34565115-89eb1880-f194-11e7-9ea4-27643d4559d1.png)

**Comment by skygragon** [comment]
That's a known mismatch of leetcode.com itself, it uses 2 different ids for same question, e.g.

```json
{
  "status": null,
  "stat": {
    "total_acs": 2054,
    "question__title": "Closest Leaf in a Binary Tree",
    "is_new_question": false,
    "question__article__slug": "closest-leaf-in-binary-tree",
    "total_submitted": 6307,
    "frontend_question_id": 742,
    "question__title_slug": "closest-leaf-in-a-binary-tree",
    "question__article__live": true,
    "question__hide": false,
    "question_id": 743
}
```

You see for this "Closest Leaf in a Binary Tree", its backend id is 743 (used by leetcode-cli), while its frontend id is 742 (shown on webpage).

I guess leetcode.com is not showing all the questions to users (e.g. some very new questions are usually filtered out, or some questions are deleted for some reason?), anyway, there are gaps in the list, but on web page they try to hide those gaps thus invent a "frontend id" to work around this. Well it's just a bold guess.

**Comment by skygragon** [comment]
@shaodan btw, what's your terminal in the screenshot above? I notice the list output is not well aligned, I guess it's caused by a non-mono font?

**Comment by shaodan** [comment]
@skygragon I'm visiting a jupyter terminal console, seems chrome cannot display check icon and lock icon with monospace font.

**Comment by skygragon** [comment]
@shaodan could you try this latest commit to see if the id matches the web page?
```
$ npm install -g skygragon/leetcode-cli
```
Please let me know if there are new issues caused by this commit.

**Comment by shaodan** [comment]
@skygragon It works! thanks for your quick response.
