### ISSUE TITLE
Possible to store account credentials locally so we don't have to signout/signin frequently?

### ISSUE THREAD

**Issue by PrincipalsOffice** [skygragon/leetcode-cli#85]
### Problem Summary

I know this is probably a big security concern, but since Leetcode only allows single sign on, it becomes quite annoying to frequently signout-signin again and again. It will be nice for some users to be able to login with just one command. 

Anyone know what are some good solutions for this (storing credentials locally)?
### Environment

- leetcode-cli version:

- OS version:
- Node version:
- Npm version:

**Comment by skygragon** [comment]
would this help?

https://skygragon.github.io/leetcode-cli/advanced#auto-login
