### ISSUE TITLE
Not supported language "java" error when generating source code

### ISSUE THREAD

**Issue by weili11864** [skygragon/leetcode-cli#87]
### Problem Summary

I use "leetcode show -g -x -l java 175" to generate source code, but encountered the following exception:

[ERROR] Not supported language "java" [0]
[WARN] Supported languages:  mysql

I have used the same command to generate all source code before question 175.

### Environment

- leetcode-cli version: v2.5.1

- OS version: darwin 16.7.0
- Node version: v9.2.1
- Npm version: v5.6.0

**Comment by skygragon** [comment]
175 is a database question, not algorithm question, try following instead:
```
leetcode show -g -x -l mysql 175
```

**Comment by LVRANRAN** [comment]
Have you solved the problem at last? I've met the same question...
