### ISSUE TITLE
Have detail output for Submission

### ISSUE THREAD

**Issue by gynet** [skygragon/leetcode-cli#9]
It would be nice not only show how many test passed/failed, but also detail output especially for errors.

**Comment by skygragon** [comment]
Need more info about this, do you mean the output of 'submit' command?

**Comment by gynet** [comment]
After using "lc submit",  if there is any error, the console would only show "✘ Compile Error"or "✘ Runtime Error" instead of details exception message/messages.

**Comment by skygragon** [comment]
Got it and please try the latest fix. Also note that for runtime error there is no detail msg returned from leetcode.com, while the failed case is out there thus you can still debug that specific testcase with "test" command.

**Comment by gynet** [comment]
Ok, saw output got enhanced. It looks better now.
