### ISSUE TITLE
 Problem not found!

### ISSUE THREAD

**Issue by mtortorise** [skygragon/leetcode-cli#90]
### Problem Summary

Hi, I got the error '[ERROR] Problem not found! [0]' when I use the command 'leetcode show 457 -gxl java'. I am able to obtain other problems with the same command. Also I could found the problem in the website. 
### Environment

- leetcode-cli version: 2.5.1

- OS version:
- Node version:
- Npm version: 5.6.0

**Comment by skygragon** [comment]
please clear cache and try again?
```
leetcode cache -d problems
```

**Comment by mtortorise** [comment]
I clear the cache, but it does not help. And I found Problem 458 is not available either.

**Comment by skygragon** [comment]
@mtortorise Thanks for reporting this!

Seems leetcode.com doesn't include question 457 or 458 in the json list: https://leetcode.com/api/problems/algorithms/, sounds a bug of leetcode.com itself?
