### ISSUE TITLE
Failed to load locked problem

### ISSUE THREAD

**Issue by yuzhoul1991** [skygragon/leetcode-cli#91]
### Problem Summary
It is no longer able to show and download the locked questions all of a sudden. I am still premium member. 

### How to reproduce

> $ leetcode show 298 -g -vv                                                                                                                               ⬡ 9.4.0
[TRACE] initializing all plugins
[TRACE] found plugin: cache=default
[TRACE] inited plugin: cache
[TRACE] found plugin: company=2017.12.18
[TRACE] inited plugin: company
[TRACE] found plugin: cpp.run=2017.07.29
[TRACE] inited plugin: cpp.run
[TRACE] found plugin: github=2018.01.06
[TRACE] inited plugin: github
[TRACE] found plugin: leetcode=default
[TRACE] inited plugin: leetcode
[TRACE] found plugin: retry=default
[TRACE] inited plugin: retry
[TRACE] missing plugins: 0
[DEBUG] cache hit: problems.json
[DEBUG] running leetcode.getProblem
[ERROR] failed to load locked problem! [0]

### Environment

leetcode version returns 2.5.1

- leetcode-cli version:

- OS version:

redhat, not sure what version, it was working just a few days ago i think

- Node version:

v9.4.0

- Npm version:
5.6.0

**Comment by skygragon** [comment]
@yuzhoul1991 Have you tried manually re-login?

**Comment by yuzhoul1991** [comment]
You mean leetcode user -l? If so yes I tried that 

Best,
Yuzhou

**Comment by skygragon** [comment]
There might be a bug if we have old problems.json cached, please try to clear the cache? I don't have premium account thus can't test it all.

```
leetcode cache -d problems
```

**Comment by 15cm** [comment]
Same problem here. Even after clear the cache by `leetcode cache -d`.

**Comment by 15cm** [comment]
Maybe we can try to fetch the subscription state from [leetcode.com/subscription/](https://leetcode.com/subscription/).

I currently delete lib/plugins/leetcode.js:123 as a temporary fix for myself.

**Comment by yunweiyuan** [comment]
Facing the same issue. But still cannot accessing the locked problem after deleting lib/plugins/leetcode.js:123, or manually setting user.paid to true.

**Comment by better365** [comment]
I am running into the same issue as well. Tried upgrading to the latest version and deleting the cache. Nothing worked yet.

**Comment by yyang325** [comment]
Facing same error here.

**Comment by hankok** [comment]
Same

**Comment by skygragon** [comment]
@all feel free to try https://github.com/skygragon/leetcode-cli/pull/96 to temporarily bypass the premium user check in leetcode-cli. I can't test it myself because I don't have a premium account...

**Comment by sfdye** [comment]
Facing the same issue. @skygragon Would you mind cutting a new release to include the master fix fc7a09b7efcdb1cc3a8bdd88b857c7bc1f8cc078?

**Comment by XingyuGuUCSD** [comment]
any update?

**Comment by skygragon** [comment]
@sfdye does fc7a09b fix the issue? if so, I would kickoff a new release for it.

**Comment by sfdye** [comment]
Yes it does. Please do.

**Comment by yanzhang0219** [comment]
@skygragon Thanks. Btw, I installed it using 'npm install -g skygragon/leetcode-cli', i.e., the DEV version from GitHub which is now under 2.5.2. How to update it to 2.5.3? I just tried 'npm update -g skygragon/leetcode-cli' but nothing happened.

**Comment by skygragon** [comment]
@yanzhang0219 the last resort is to uninstall fist then install again :)

**Comment by yanzhang0219** [comment]
@skygragon Yep, that's what I did. Thanks.
