### ISSUE TITLE
Cannot login due to undefined `id_hash`

### ISSUE THREAD

**Issue by ptopenny** [skygragon/leetcode-cli#92]
### How to reproduce

1. `leetcode user -l -vv`
2. Getting `id_hash` undefined at `leetcode.js`, expecting login success
```
[TRACE] REQUEST %s end event https://leetcode.com/list/api/questions
[TRACE] REQUEST %s has body https://leetcode.com/list/api/questions 38249
[TRACE] REQUEST %s emitting complete https://leetcode.com/list/api/questions
/Users/cliff.tan/workspace/misc/leetcode-cli/lib/plugins/leetcode.js:461
    user.hash = favorite.id_hash;
                         ^

TypeError: Cannot read property 'id_hash' of undefined
    at /Users/cliff.tan/workspace/misc/leetcode-cli/lib/plugins/leetcode.js:461:26
    at Request._callback (/Users/cliff.tan/workspace/misc/leetcode-cli/lib/plugins/leetcode.js:376:12)
    at Request.self.callback (/Users/cliff.tan/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/cliff.tan/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/cliff.tan/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
```

### Environment

- leetcode-cli version: 2.5.1
- git last commit: 1cee26c47006aafc13393b5221f927b7de0f3e05

- OS version: macOS High Sierra 10.13.3
- Node version: 9.2.1
- Npm version: 5.6.0

**Comment by ptopenny** [comment]
correct me if I'm wrong, but this happens when it is trying to hit the `https://leetcode.com/list/api/questions` endpoint. Is there any changes around this endpoint?

**Comment by ptopenny** [comment]
I fixed that my commenting out line 461 in `leetcode.js` but I'm not sure if that's a long term solution.

```
plugin.getUser = function(user, cb) {
  plugin.getFavorites(function(e, favorites) {
    if (e) return cb(e);

    const favorite = favorites.favorites.private_favorites.find(function(f) {
      return f.name === 'Favorite';
    });
    //user.hash = favorite.id_hash;
    user.name = favorites.user_name;
    session.saveUser(user);
    return cb(null, user);
  });
};
```

**Comment by skygragon** [comment]
Do you ever have "star" any questions no matter via cli or website? If not, that might be a bug that "https://leetcode.com/list/api/questions" would return without a valid id_hash.

**Comment by ptopenny** [comment]
I do have some favorite questions on website (not star though). I have removed all favorite questions on website and uncomment line `461` but it still complained about the hash

**Comment by futuristek** [comment]
After removing the stars from favorite list, I was able to login.

**Comment by rojiani** [comment]
After setting my Favorites list to private, I no longer received this error...
