### ISSUE TITLE
about leetcode-cn.com

### ISSUE THREAD

**Issue by luchenqun** [skygragon/leetcode-cli#93]
I am Chinese leetcoder。this is the website: https://leetcode-cn.com
Can you provide config to get Chinese problem description and Others.
for example, when i run command"leetcode show 3 -g -l cpp" i get:
[3] Longest Substring Without Repeating Characters

https://leetcode-cn.com/problems/longest-substring-without-repeating-characters/description/

* algorithms
* Medium (18.53%)
* Source Code:       3.longest-substring-without-repeating-characters.2.cpp
* Total Accepted:    705
* Total Submissions: 3.9K
* Testcase Example:  '"abcabcbb"'
Given a string, find the length of the longest substring without repeating characters.
Examples:
Given "abcabcbb", the answer is "abc", which the length is 3.
Given "bbbbb", the answer is "b", with the length of 1.
Given "pwwkew", the answer is "wke", with the length of 3. Note that the answer must be a substring, "pwke" is a subsequence and not a substring.

I wish to get
[3] Longest Substring Without Repeating Characters
https://leetcode-cn.com/problems/longest-substring-without-repeating-characters/description/
* algorithms
* Medium (18.53%)
* Source Code:       3.longest-substring-without-repeating-characters.2.cpp
* Total Accepted:    705
* Total Submissions: 3.9K
* Testcase Example:  '"abcabcbb"'
给定一个字符串，找出不含有重复字符的 最长子串 的长度。
示例：
给定 "abcabcbb" ，没有重复字符的最长子串是 "abc" ，那么长度就是3。
给定 "bbbbb" ，最长的子串就是 "b" ，长度是1。
给定 "pwwkew" ，最长子串是 "wke" ，长度是3。请注意答案必须是一个子串，"pwke" 是 子序列 而不是子串。

**Comment by luchenqun** [comment]
原来作者也是中文的啊。哈哈哈。

**Comment by skygragon** [comment]
worth a try to simply replace "leetcode.com" with "leetcode-cn.com" in lib/config.js

**Comment by Ayanokouji-Kenn** [comment]
I had replaced the urls in config.js and relogin. the problem description is also English.
After I submit the solution,the problem became accepted  on  https://leetcode-cn.com yet.
And some problems  is not the latest version?Index of easy array problems is 766 now,but `leetcode list -q e array`only show 697

**Comment by EINDEX** [comment]
I wrote some codes to modify the graphql request.So that it can supportChinese content. I haven’t tested it on the https://leetcode. com yet.

This is my first time writing nodejs code. it might have some flaws in it , please let me know if you find one .

**Comment by skygragon** [comment]
Good job! @EINDEX 
Sorry I don't have a full test against leetcode-cn.com thus not sure if everything (e.g. list/show/test/submit) work the same as leetcode.com. I was told that leetcode-cli could easily talk to leetcode-cn.com by replacing all the URLs configs in leetcode-cli. I'm assuming you did the same while not sure if you ever hit other issues with leetcode-cn.com?

**Comment by EINDEX** [comment]
@skygragon 
The other functions work properly. I just replace "leetcode.com" with "leetcode-cn.com" in lib/config.js .

**Comment by skygragon** [comment]
@all a lightweight plugin "leetcode.cn" is available in https://github.com/skygragon/leetcode-cli-plugins/. Basically it does nothing magical except replacing the urls used in leetcode-cli.
