### ISSUE TITLE
ERROR] /bin/sh: 1: --filter=-legal/copyright,-build/include_what_you_use: not found

### ISSUE THREAD

**Issue by Dyleaf** [skygragon/leetcode-cli#95]
when i try to test my code, the error come with that node as follow:
```
$ leetcode test 1.two-sum.cpp
Input data:
[2,7,11,15]
9
Running cpplint ...
[ERROR] /bin/sh: 1: --filter=-legal/copyright,-build/include_what_you_use: not found
```
but  when i try to submit,it worked.
```
$ leetcode submit 1.two-sum.cpp
  ✔ Accepted
  ✔ 20/20 cases passed (161 ms)
  ✔ Your runtime beats 30.92 % of cpp submissions
```
 by the way, my environment is ubuntu 16.04 and I use zsh to replace bash.the other as follow: 
```
node -v                            v8.11.1
npm -v                               5.6.0
leetcode version           2.5.1
```

**Comment by skygragon** [comment]
this should be opened in https://github.com/skygragon/leetcode-cli-plugins

seems like leetcode-cli doesn't find cpplint.py, do you config cpp.lint plugin correctly?

**Comment by Dyleaf** [comment]
Thank you,that solved my problem.
